VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Main"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Function ToolWndProc(lngHandle As Long, Optional Reserved As Long) As Boolean
    Load frmToolMain
    frmToolMain.Show
    Do
        DoEvents
    Loop While frmToolMain.Visible = True
End Function
